cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs && wget -x -np http://thehoseys.org/buster/mm000001.zip
  cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs && wget -x -np http://thehoseys.org/buster/mm000001.zip


cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm000001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm000501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm001001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm001501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm002001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm002501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm003001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm003501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm004001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm004501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm005001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm005501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm006001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm006501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm007001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm007501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm008001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm008501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm009001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm009501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm010001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm010501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm011001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm011501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm012001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm012501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm013001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm013501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm014001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm014501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm015001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm015501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm016001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm016501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm017001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm017501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm018001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm018501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm019001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm019501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm020001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm020501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm021001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm021501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm022001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm022501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm023001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm023501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm024001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm024501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm025001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm025501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm026001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm026501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm027001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm027501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm028001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm028501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm029001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm029501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm030001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm030501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm031001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm031501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm032001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm032501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm033001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm033501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm034001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm034501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm035001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm035501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm036001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm036501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm037001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm037501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm038001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm038501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm039001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm039501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm040001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm040501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm041001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm041501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm042001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm042501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm043001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm043501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm044001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm044501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm045001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm045501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm046001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm046501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm047001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm047501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm048001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm048501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm049001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm049501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm050001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm050501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm051001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm051501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm052001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm052501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm053001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm053501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm054001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm054501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm055001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm055501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm056001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm056501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm057001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm057501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm058001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm058501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm059001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm059501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm060001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm060501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm061001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm061501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm062001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm062501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm063001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm063501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm064001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm064501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm065001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm065501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm066001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm066501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm067001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm067501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm068001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm068501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm069001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm069501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm070001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm070501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm071001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm071501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm072001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm072501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm073001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm073501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm074001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm074501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm075001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm075501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm076001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm076501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm077001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm077501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm078001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm078501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm079001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm079501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm080001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm080501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm081001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm081501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm082001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm082501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm083001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm083501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm084001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm084501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm085001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm085501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm086001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm086501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm087001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm087501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm088001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm088501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm089001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm089501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm090001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm090501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm091001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm091501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm092001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm092501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm093001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm093501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm094001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm094501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm095001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm095501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm096001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm096501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm097001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm097501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm098001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm098501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm099001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm099501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm100001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm100501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm101001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm101501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm102001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm102501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm103001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm103501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm104001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm104501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm105001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm105501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm106001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm106501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm107001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm107501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm108001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm108501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm109001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm109501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm110001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm110501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm111001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm111501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm112001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm112501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm113001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm113501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm114001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm114501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm115001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm115501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm116001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm116501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm117001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm117501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm118001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm118501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm119001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm119501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm120001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm120501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm121001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm121501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm122001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm122501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm123001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm123501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm124001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm124501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm125001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm125501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm126001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm126501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm127001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm127501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm128001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm128501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm129001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm129501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm130001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm130501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm131001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm131501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm132001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm132501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm133001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm133501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm134001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm134501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm135001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm135501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm136001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm136501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm137001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm137501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm138001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm138501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm139001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm139501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm140001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm140501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm141001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm141501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm142001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm142501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm143001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm143501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm144001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm144501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm145001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm145501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm146001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm146501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm147001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm147501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm148001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm148501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm149001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm149501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm150001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm150501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm151001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm151501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm152001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm152501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm153001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm153501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm154001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm154501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm155001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm155501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm156001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm156501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm157001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm157501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm158001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm158501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm159001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm159501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm160001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm160501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm161001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm161501.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm162001.zip
cd /var/lib/myfrdcsa/codebases/internal/gourmet/data/recs/ && wget -x -np http://thehoseys.com/buster/mm162501.zip
